/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppButton {
        /**
          * @default 'Continue'
         */
        "label": string;
        /**
          * @default 'button'
         */
        "type": 'button' | 'submit';
        /**
          * @default 'primary'
         */
        "variant": 'primary' | 'secondary' | 'danger';
    }
    interface MealPlanner {
        /**
          * @default ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
         */
        "days": string[];
        /**
          * @default {}
         */
        "meals": Record<string, string>;
    }
    interface RecipeCard {
        /**
          * @default 'International'
         */
        "cuisine": string;
        /**
          * @default 'A delicious recipe'
         */
        "description": string;
        /**
          * @default false
         */
        "favorite": boolean;
        /**
          * @default ''
         */
        "image": string;
        /**
          * @default 'Recipe'
         */
        "recipeTitle": string;
    }
    interface RecipeFilter {
        /**
          * @default ['all', 'breakfast', 'lunch', 'dinner', 'dessert']
         */
        "options": string[];
        /**
          * @default 'all'
         */
        "selected": string;
    }
    interface RecipeModal {
        /**
          * @default 'Recipe details'
         */
        "modalTitle": string;
        /**
          * @default false
         */
        "open": boolean;
    }
    interface RecipeSearch {
        /**
          * @default 'Search for recipes'
         */
        "placeholder": string;
        /**
          * @default ''
         */
        "value": string;
    }
}
export interface AppButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAppButtonElement;
}
export interface MealPlannerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMealPlannerElement;
}
export interface RecipeCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRecipeCardElement;
}
export interface RecipeFilterCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRecipeFilterElement;
}
export interface RecipeModalCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRecipeModalElement;
}
export interface RecipeSearchCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRecipeSearchElement;
}
declare global {
    interface HTMLAppButtonElementEventMap {
        "clickAction": void;
    }
    interface HTMLAppButtonElement extends Components.AppButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAppButtonElementEventMap>(type: K, listener: (this: HTMLAppButtonElement, ev: AppButtonCustomEvent<HTMLAppButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAppButtonElementEventMap>(type: K, listener: (this: HTMLAppButtonElement, ev: AppButtonCustomEvent<HTMLAppButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAppButtonElement: {
        prototype: HTMLAppButtonElement;
        new (): HTMLAppButtonElement;
    };
    interface HTMLMealPlannerElementEventMap {
        "removeMeal": string;
    }
    interface HTMLMealPlannerElement extends Components.MealPlanner, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMealPlannerElementEventMap>(type: K, listener: (this: HTMLMealPlannerElement, ev: MealPlannerCustomEvent<HTMLMealPlannerElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMealPlannerElementEventMap>(type: K, listener: (this: HTMLMealPlannerElement, ev: MealPlannerCustomEvent<HTMLMealPlannerElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMealPlannerElement: {
        prototype: HTMLMealPlannerElement;
        new (): HTMLMealPlannerElement;
    };
    interface HTMLRecipeCardElementEventMap {
        "selectRecipe": { title: string; image: string; description: string; cuisine: string };
        "toggleFavorite": { title: string; favorite: boolean };
    }
    interface HTMLRecipeCardElement extends Components.RecipeCard, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRecipeCardElementEventMap>(type: K, listener: (this: HTMLRecipeCardElement, ev: RecipeCardCustomEvent<HTMLRecipeCardElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRecipeCardElementEventMap>(type: K, listener: (this: HTMLRecipeCardElement, ev: RecipeCardCustomEvent<HTMLRecipeCardElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRecipeCardElement: {
        prototype: HTMLRecipeCardElement;
        new (): HTMLRecipeCardElement;
    };
    interface HTMLRecipeFilterElementEventMap {
        "filterChange": string;
    }
    interface HTMLRecipeFilterElement extends Components.RecipeFilter, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRecipeFilterElementEventMap>(type: K, listener: (this: HTMLRecipeFilterElement, ev: RecipeFilterCustomEvent<HTMLRecipeFilterElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRecipeFilterElementEventMap>(type: K, listener: (this: HTMLRecipeFilterElement, ev: RecipeFilterCustomEvent<HTMLRecipeFilterElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRecipeFilterElement: {
        prototype: HTMLRecipeFilterElement;
        new (): HTMLRecipeFilterElement;
    };
    interface HTMLRecipeModalElementEventMap {
        "closeModal": void;
    }
    interface HTMLRecipeModalElement extends Components.RecipeModal, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRecipeModalElementEventMap>(type: K, listener: (this: HTMLRecipeModalElement, ev: RecipeModalCustomEvent<HTMLRecipeModalElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRecipeModalElementEventMap>(type: K, listener: (this: HTMLRecipeModalElement, ev: RecipeModalCustomEvent<HTMLRecipeModalElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRecipeModalElement: {
        prototype: HTMLRecipeModalElement;
        new (): HTMLRecipeModalElement;
    };
    interface HTMLRecipeSearchElementEventMap {
        "searchInput": string;
    }
    interface HTMLRecipeSearchElement extends Components.RecipeSearch, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRecipeSearchElementEventMap>(type: K, listener: (this: HTMLRecipeSearchElement, ev: RecipeSearchCustomEvent<HTMLRecipeSearchElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRecipeSearchElementEventMap>(type: K, listener: (this: HTMLRecipeSearchElement, ev: RecipeSearchCustomEvent<HTMLRecipeSearchElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRecipeSearchElement: {
        prototype: HTMLRecipeSearchElement;
        new (): HTMLRecipeSearchElement;
    };
    interface HTMLElementTagNameMap {
        "app-button": HTMLAppButtonElement;
        "meal-planner": HTMLMealPlannerElement;
        "recipe-card": HTMLRecipeCardElement;
        "recipe-filter": HTMLRecipeFilterElement;
        "recipe-modal": HTMLRecipeModalElement;
        "recipe-search": HTMLRecipeSearchElement;
    }
}
declare namespace LocalJSX {
    interface AppButton {
        /**
          * @default 'Continue'
         */
        "label"?: string;
        "onClickAction"?: (event: AppButtonCustomEvent<void>) => void;
        /**
          * @default 'button'
         */
        "type"?: 'button' | 'submit';
        /**
          * @default 'primary'
         */
        "variant"?: 'primary' | 'secondary' | 'danger';
    }
    interface MealPlanner {
        /**
          * @default ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
         */
        "days"?: string[];
        /**
          * @default {}
         */
        "meals"?: Record<string, string>;
        "onRemoveMeal"?: (event: MealPlannerCustomEvent<string>) => void;
    }
    interface RecipeCard {
        /**
          * @default 'International'
         */
        "cuisine"?: string;
        /**
          * @default 'A delicious recipe'
         */
        "description"?: string;
        /**
          * @default false
         */
        "favorite"?: boolean;
        /**
          * @default ''
         */
        "image"?: string;
        "onSelectRecipe"?: (event: RecipeCardCustomEvent<{ title: string; image: string; description: string; cuisine: string }>) => void;
        "onToggleFavorite"?: (event: RecipeCardCustomEvent<{ title: string; favorite: boolean }>) => void;
        /**
          * @default 'Recipe'
         */
        "recipeTitle"?: string;
    }
    interface RecipeFilter {
        "onFilterChange"?: (event: RecipeFilterCustomEvent<string>) => void;
        /**
          * @default ['all', 'breakfast', 'lunch', 'dinner', 'dessert']
         */
        "options"?: string[];
        /**
          * @default 'all'
         */
        "selected"?: string;
    }
    interface RecipeModal {
        /**
          * @default 'Recipe details'
         */
        "modalTitle"?: string;
        "onCloseModal"?: (event: RecipeModalCustomEvent<void>) => void;
        /**
          * @default false
         */
        "open"?: boolean;
    }
    interface RecipeSearch {
        "onSearchInput"?: (event: RecipeSearchCustomEvent<string>) => void;
        /**
          * @default 'Search for recipes'
         */
        "placeholder"?: string;
        /**
          * @default ''
         */
        "value"?: string;
    }

    interface AppButtonAttributes {
        "label": string;
        "variant": 'primary' | 'secondary' | 'danger';
        "type": 'button' | 'submit';
    }
    interface RecipeCardAttributes {
        "recipeTitle": string;
        "image": string;
        "description": string;
        "cuisine": string;
        "favorite": boolean;
    }
    interface RecipeFilterAttributes {
        "selected": string;
    }
    interface RecipeModalAttributes {
        "open": boolean;
        "modalTitle": string;
    }
    interface RecipeSearchAttributes {
        "value": string;
        "placeholder": string;
    }

    interface IntrinsicElements {
        "app-button": Omit<AppButton, keyof AppButtonAttributes> & { [K in keyof AppButton & keyof AppButtonAttributes]?: AppButton[K] } & { [K in keyof AppButton & keyof AppButtonAttributes as `attr:${K}`]?: AppButtonAttributes[K] } & { [K in keyof AppButton & keyof AppButtonAttributes as `prop:${K}`]?: AppButton[K] };
        "meal-planner": MealPlanner;
        "recipe-card": Omit<RecipeCard, keyof RecipeCardAttributes> & { [K in keyof RecipeCard & keyof RecipeCardAttributes]?: RecipeCard[K] } & { [K in keyof RecipeCard & keyof RecipeCardAttributes as `attr:${K}`]?: RecipeCardAttributes[K] } & { [K in keyof RecipeCard & keyof RecipeCardAttributes as `prop:${K}`]?: RecipeCard[K] };
        "recipe-filter": Omit<RecipeFilter, keyof RecipeFilterAttributes> & { [K in keyof RecipeFilter & keyof RecipeFilterAttributes]?: RecipeFilter[K] } & { [K in keyof RecipeFilter & keyof RecipeFilterAttributes as `attr:${K}`]?: RecipeFilterAttributes[K] } & { [K in keyof RecipeFilter & keyof RecipeFilterAttributes as `prop:${K}`]?: RecipeFilter[K] };
        "recipe-modal": Omit<RecipeModal, keyof RecipeModalAttributes> & { [K in keyof RecipeModal & keyof RecipeModalAttributes]?: RecipeModal[K] } & { [K in keyof RecipeModal & keyof RecipeModalAttributes as `attr:${K}`]?: RecipeModalAttributes[K] } & { [K in keyof RecipeModal & keyof RecipeModalAttributes as `prop:${K}`]?: RecipeModal[K] };
        "recipe-search": Omit<RecipeSearch, keyof RecipeSearchAttributes> & { [K in keyof RecipeSearch & keyof RecipeSearchAttributes]?: RecipeSearch[K] } & { [K in keyof RecipeSearch & keyof RecipeSearchAttributes as `attr:${K}`]?: RecipeSearchAttributes[K] } & { [K in keyof RecipeSearch & keyof RecipeSearchAttributes as `prop:${K}`]?: RecipeSearch[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-button": LocalJSX.IntrinsicElements["app-button"] & JSXBase.HTMLAttributes<HTMLAppButtonElement>;
            "meal-planner": LocalJSX.IntrinsicElements["meal-planner"] & JSXBase.HTMLAttributes<HTMLMealPlannerElement>;
            "recipe-card": LocalJSX.IntrinsicElements["recipe-card"] & JSXBase.HTMLAttributes<HTMLRecipeCardElement>;
            "recipe-filter": LocalJSX.IntrinsicElements["recipe-filter"] & JSXBase.HTMLAttributes<HTMLRecipeFilterElement>;
            "recipe-modal": LocalJSX.IntrinsicElements["recipe-modal"] & JSXBase.HTMLAttributes<HTMLRecipeModalElement>;
            "recipe-search": LocalJSX.IntrinsicElements["recipe-search"] & JSXBase.HTMLAttributes<HTMLRecipeSearchElement>;
        }
    }
}
